import { AcademicGenre, ReviewDimension, BriefIntention } from './types';

/* ==========================================================
   Academic Genres — Each has specific structure + criteria
   ========================================================== */

export const ACADEMIC_GENRES: AcademicGenre[] = [
  {
    id: 'ensayo',
    name: 'Ensayo académico',
    icon: '📝',
    description: 'Texto argumentativo que presenta y defiende una postura sobre un tema específico.',
    structureComponents: [
      'Introducción y presentación del tema',
      'Planteamiento de tesis o idea central',
      'Desarrollo argumentativo',
      'Organización de los párrafos',
      'Uso de evidencias y fuentes',
      'Coherencia entre los argumentos',
      'Conclusión',
      'Registro académico',
    ],
    evaluationCriteria: [
      { name: 'Tesis clara', description: 'La postura central debe estar formulada de manera explícita y defendible.' },
      { name: 'Argumentación sólida', description: 'Los argumentos deben estar justificados con evidencias, razonamientos o fuentes.' },
      { name: 'Coherencia interna', description: 'Los párrafos deben estar conectados lógicamente y contribuir a la defensa de la tesis.' },
      { name: 'Conclusión articulada', description: 'La conclusión debe sintetizar la postura defendida sin introducir ideas nuevas sin desarrollo.' },
    ],
    notes: null,
  },
  {
    id: 'articulo_cientifico',
    name: 'Artículo científico',
    icon: '🔬',
    description: 'Publicación que comunica resultados de una investigación original siguiendo un formato estandarizado.',
    structureComponents: [
      'Título',
      'Resumen (Abstract)',
      'Palabras clave',
      'Introducción',
      'Metodología',
      'Resultados',
      'Discusión',
      'Conclusiones',
      'Referencias bibliográficas',
    ],
    evaluationCriteria: [
      { name: 'Estructura IMRyD', description: 'El artículo sigue la estructura Introducción-Metodología-Resultados-Discusión, aunque puede variar según la disciplina.' },
      { name: 'Objetividad', description: 'El lenguaje debe ser impersonal y basado en datos.' },
      { name: 'Reproducibilidad', description: 'La metodología debe ser lo suficientemente detallada para permitir la replicación.' },
      { name: 'Coherencia con resultados', description: 'Las conclusiones deben derivarse lógicamente de los resultados presentados.' },
    ],
    notes: 'No todos los artículos científicos siguen exactamente la misma estructura. Existen variaciones según la disciplina, la revista y el formato editorial.',
  },
  {
    id: 'informe_tecnico',
    name: 'Informe técnico',
    icon: '📊',
    description: 'Documento que presenta el análisis técnico de un problema, procedimiento o situación.',
    structureComponents: [
      'Identificación del problema u objetivo',
      'Descripción del procedimiento o metodología',
      'Presentación de resultados o hallazgos',
      'Análisis e interpretación',
      'Conclusiones',
      'Recomendaciones',
      'Organización de apartados',
    ],
    evaluationCriteria: [
      { name: 'Claridad técnica', description: 'La información técnica debe presentarse de forma precisa y comprensible.' },
      { name: 'Estructura lógica', description: 'Los apartados deben seguir un orden coherente del problema a la solución.' },
      { name: 'Datos verificables', description: 'Los resultados deben estar respaldados por datos concretos.' },
    ],
    notes: null,
  },
  {
    id: 'reporte_investigacion',
    name: 'Reporte de investigación',
    icon: '🔍',
    description: 'Documento que describe el proceso y los resultados de un estudio o investigación.',
    structureComponents: [
      'Planteamiento del problema',
      'Objetivos de investigación',
      'Marco teórico o antecedentes',
      'Metodología',
      'Resultados',
      'Análisis y discusión',
      'Conclusiones',
      'Referencias',
    ],
    evaluationCriteria: [
      { name: 'Coherencia metodológica', description: 'Los métodos deben ser congruentes con los objetivos planteados.' },
      { name: 'Fundamentación', description: 'El marco teórico debe sustentar la investigación realizada.' },
      { name: 'Objetividad', description: 'Los resultados deben presentarse sin sesgos interpretativos indebidos.' },
    ],
    notes: null,
  },
  {
    id: 'resumen_academico',
    name: 'Resumen académico',
    icon: '📋',
    description: 'Texto breve que condensa las ideas principales de un documento más extenso.',
    structureComponents: [
      'Identificación del texto fuente',
      'Idea principal del texto',
      'Ideas secundarias relevantes',
      'Fidelidad al contenido original',
      'Brevedad y concisión',
    ],
    evaluationCriteria: [
      { name: 'Fidelidad', description: 'El resumen debe representar con precisión las ideas del texto original.' },
      { name: 'Selección de ideas', description: 'Debe distinguir ideas principales de secundarias e incluir las esenciales.' },
      { name: 'Concisión', description: 'Debe ser significativamente más breve que el texto original sin perder información clave.' },
      { name: 'No interpretación', description: 'No debe incluir opiniones o interpretaciones propias del redactor.' },
    ],
    notes: null,
  },
  {
    id: 'sintesis',
    name: 'Síntesis',
    icon: '🔗',
    description: 'Texto que integra ideas de varias fuentes para construir una visión global.',
    structureComponents: [
      'Identificación de fuentes',
      'Ideas principales integradas',
      'Relaciones entre fuentes',
      'Visión global coherente',
      'Voz propia del autor',
    ],
    evaluationCriteria: [
      { name: 'Integración de fuentes', description: 'Las ideas de las distintas fuentes deben estar articuladas, no simplemente yuxtapuestas.' },
      { name: 'Aporte propio', description: 'La síntesis debe ofrecer una perspectiva integradora, no solo un resumen combinado.' },
      { name: 'Coherencia global', description: 'El texto debe leerse como un todo articulado.' },
    ],
    notes: null,
  },
  {
    id: 'resena_critica',
    name: 'Reseña crítica',
    icon: '⚖️',
    description: 'Texto que describe y evalúa críticamente una obra, artículo o documento.',
    structureComponents: [
      'Datos de la obra reseñada',
      'Descripción del contenido',
      'Análisis crítico',
      'Valoración fundamentada',
      'Postura del reseñador',
      'Conclusión',
    ],
    evaluationCriteria: [
      { name: 'Descripción fiel', description: 'El contenido de la obra debe describirse con precisión antes de ser evaluado.' },
      { name: 'Argumentación crítica', description: 'Las valoraciones deben estar sustentadas con argumentos, no ser opiniones sin fundamento.' },
      { name: 'Equilibrio', description: 'Debe reconocer tanto fortalezas como debilidades de la obra, cuando las haya.' },
    ],
    notes: null,
  },
  {
    id: 'monografia',
    name: 'Monografía',
    icon: '📚',
    description: 'Estudio detallado y exhaustivo sobre un tema específico, basado en fuentes documentales.',
    structureComponents: [
      'Introducción y delimitación del tema',
      'Justificación',
      'Objetivos',
      'Desarrollo temático',
      'Marco conceptual',
      'Conclusiones',
      'Bibliografía',
    ],
    evaluationCriteria: [
      { name: 'Profundidad', description: 'El tema debe tratarse con suficiente detalle y exhaustividad.' },
      { name: 'Fundamentación documental', description: 'Las afirmaciones deben estar respaldadas por fuentes bibliográficas.' },
      { name: 'Organización temática', description: 'Los apartados deben seguir un desarrollo lógico del tema.' },
    ],
    notes: null,
  },
  {
    id: 'protocolo_investigacion',
    name: 'Protocolo de investigación',
    icon: '📐',
    description: 'Documento que planifica y describe cómo se llevará a cabo una investigación.',
    structureComponents: [
      'Título del proyecto',
      'Planteamiento del problema',
      'Pregunta de investigación',
      'Objetivos',
      'Justificación',
      'Marco teórico',
      'Hipótesis (si aplica)',
      'Metodología propuesta',
      'Cronograma',
      'Referencias',
    ],
    evaluationCriteria: [
      { name: 'Viabilidad', description: 'La metodología propuesta debe ser realizable con los recursos disponibles.' },
      { name: 'Coherencia interna', description: 'Debe haber congruencia entre problema, objetivos, hipótesis y metodología.' },
      { name: 'Claridad del diseño', description: 'El plan de trabajo debe ser comprensible y seguible.' },
    ],
    notes: null,
  },
  {
    id: 'marco_teorico',
    name: 'Marco teórico',
    icon: '🏗️',
    description: 'Sección que establece los fundamentos conceptuales y teóricos de una investigación.',
    structureComponents: [
      'Antecedentes de investigación',
      'Bases teóricas',
      'Definición de conceptos clave',
      'Relación entre conceptos',
      'Fundamentación bibliográfica',
    ],
    evaluationCriteria: [
      { name: 'Pertinencia', description: 'Las teorías y conceptos incluidos deben ser relevantes para la investigación.' },
      { name: 'Articulación', description: 'Los conceptos deben estar conectados entre sí y con el problema de investigación.' },
      { name: 'Actualización', description: 'Las fuentes deben ser relevantes y, cuando sea posible, actualizadas.' },
    ],
    notes: null,
  },
  {
    id: 'estado_del_arte',
    name: 'Estado del arte',
    icon: '🗺️',
    description: 'Revisión exhaustiva de la literatura existente sobre un tema de investigación.',
    structureComponents: [
      'Delimitación del tema',
      'Criterios de búsqueda',
      'Revisión de fuentes',
      'Tendencias identificadas',
      'Vacíos en la investigación',
      'Síntesis interpretativa',
    ],
    evaluationCriteria: [
      { name: 'Exhaustividad', description: 'La revisión debe cubrir las fuentes más relevantes del tema.' },
      { name: 'Organización', description: 'Las fuentes deben estar organizadas temática o cronológicamente.' },
      { name: 'Análisis de tendencias', description: 'Debe identificar patrones, coincidencias y discrepancias entre los estudios.' },
    ],
    notes: null,
  },
  {
    id: 'reporte_practicas',
    name: 'Reporte de prácticas o laboratorio',
    icon: '🧪',
    description: 'Documento que registra los procedimientos, resultados y observaciones de una práctica experimental.',
    structureComponents: [
      'Título de la práctica',
      'Objetivo',
      'Marco teórico breve',
      'Materiales y equipo',
      'Procedimiento',
      'Resultados y datos',
      'Análisis de resultados',
      'Conclusiones',
      'Cuestionario (si aplica)',
    ],
    evaluationCriteria: [
      { name: 'Precisión', description: 'Los datos y procedimientos deben registrarse con exactitud.' },
      { name: 'Coherencia datos-conclusiones', description: 'Las conclusiones deben derivarse de los resultados obtenidos.' },
      { name: 'Claridad procedimental', description: 'El procedimiento debe ser reproducible a partir de la descripción.' },
    ],
    notes: null,
  },
  {
    id: 'tesis',
    name: 'Tesis o proyecto de investigación',
    icon: '🎓',
    description: 'Trabajo extenso de investigación que demuestra el dominio de un tema y la capacidad investigativa del autor.',
    structureComponents: [
      'Portada',
      'Índice',
      'Resumen',
      'Introducción',
      'Planteamiento del problema',
      'Justificación',
      'Objetivos',
      'Marco teórico',
      'Marco metodológico',
      'Resultados',
      'Discusión',
      'Conclusiones',
      'Recomendaciones',
      'Referencias bibliográficas',
      'Anexos',
    ],
    evaluationCriteria: [
      { name: 'Coherencia integral', description: 'Todos los capítulos deben estar articulados entre sí.' },
      { name: 'Rigor metodológico', description: 'La investigación debe seguir un método sistemático y justificado.' },
      { name: 'Originalidad', description: 'Debe aportar conocimiento nuevo o una perspectiva original sobre el tema.' },
      { name: 'Fundamentación extensa', description: 'Las afirmaciones deben estar ampliamente respaldadas por la literatura.' },
    ],
    notes: 'Las tesis varían significativamente según la institución, el nivel académico (licenciatura, maestría, doctorado) y la disciplina.',
  },
  {
    id: 'otro',
    name: 'Otro tipo de texto',
    icon: '📄',
    description: 'Especifica el género académico y sus características particulares para una evaluación personalizada.',
    structureComponents: [],
    evaluationCriteria: [],
    notes: 'El usuario deberá describir el tipo de texto y sus requisitos específicos. El sistema aplicará criterios generales razonables basados en la descripción proporcionada.',
  },
];

/* ==========================================================
   Review Dimensions (Academic Module)
   ========================================================== */

export const REVIEW_DIMENSIONS: ReviewDimension[] = [
  {
    id: 'grammar',
    name: 'Ortografía, gramática y puntuación',
    description: 'Errores ortográficos, concordancia, uso de tiempos verbales, puntuación y acentuación.',
    default: true,
  },
  {
    id: 'coherence',
    name: 'Coherencia y cohesión',
    description: 'Conexión lógica entre ideas, uso de conectores, progresión temática y estructura del discurso.',
    default: true,
  },
  {
    id: 'clarity',
    name: 'Claridad y precisión',
    description: 'Formulación clara de ideas, ausencia de ambigüedades y uso preciso del lenguaje.',
    default: true,
  },
  {
    id: 'structure',
    name: 'Estructura del género académico',
    description: 'Presencia y adecuación de los componentes estructurales propios del tipo de texto seleccionado.',
    default: true,
  },
  {
    id: 'argumentation',
    name: 'Argumentación y desarrollo de ideas',
    description: 'Solidez de los argumentos, uso de evidencias, desarrollo de ideas y fundamentación.',
    default: true,
  },
  {
    id: 'comprehension',
    name: 'Comprensión del texto de referencia',
    description: 'Fidelidad a las ideas del texto fuente, interpretación correcta y diferenciación de ideas propias.',
    default: true,
  },
  {
    id: 'integral',
    name: 'Retroalimentación integral',
    description: 'Evaluación completa que integra todas las dimensiones anteriores.',
    default: true,
  },
];

/* ==========================================================
   Brief Intentions
   ========================================================== */

export const BRIEF_INTENTIONS: BriefIntention[] = [
  { id: 'general', name: 'Revisión general', description: 'Revisión completa de ortografía, gramática, claridad y coherencia.' },
  { id: 'spelling', name: 'Ortografía y puntuación', description: 'Solo errores ortográficos, de acentuación y puntuación.' },
  { id: 'grammar_syntax', name: 'Gramática y sintaxis', description: 'Concordancia, tiempos verbales, orden sintáctico.' },
  { id: 'clarity_style', name: 'Claridad y redacción', description: 'Formulación de ideas, eliminación de ambigüedades y mejora de estilo.' },
  { id: 'coherence_cohesion', name: 'Coherencia y cohesión', description: 'Conexión entre ideas, uso de conectores, progresión temática.' },
  { id: 'formal', name: 'Registro formal', description: 'Adecuación del lenguaje a un contexto formal o profesional.' },
];
